---
apiVersion: v1
kind: Service
metadata:
  labels:
    druid: metrics
  name: {{ .Values.name }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.druidExporterPort }}
    protocol: TCP
    targetPort: {{ .Values.druidExporterPort }}
  selector:
    druid: metrics
  type: ClusterIP
