---
version: 2.1
orbs:
  helm: banzaicloud/helm@0.0.7

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/druid-exporter
    steps:
      - checkout
      - setup_remote_docker
      - run: make get-depends
      - run: make build-code
      - run: make build-image
  lint:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/druid-exporter
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -u golang.org/x/lint/golint
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
      - run: make lint
      - run: make golangci-lint
  
  bugscan:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/druid-exporter
    steps:
      - checkout
      - setup_remote_docker
      - run: make vet

workflows:
  version: 2.1
  jobs:
    - build
    - lint
    - bugscan
  helm-chart-lint:
    jobs:
      - helm/lint-chart:
          charts-dir: helm
          filters:
            tags:
              ignore: /.*/
