---
apiVersion: v1
kind: Service
metadata:
  labels:
    druid: metrics
  name: druid-exporter
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    druid: metrics
  type: ClusterIP
